### PR TITLE
 Make `proptest` optional

### LINKED ISSUE #45: Make `proptest` optional

### PR DESCRIPTION
**Pull request by hoangdt84**
Close #45

### CODE REVIEW

**Comment by hoangdt84** [comment]
This PR includes commit to resolve #44

**Comment by nyuichi** [comment]
@hoangdt84 Can you split the pr into two for each issue respectively?
And may I get a permission to push to your forked repo?

**Comment by hoangdt84** [comment]
> Can you split the pr into two for each issue respectively?
Sorry but I don't know how to drop a commit. Should I close this PR and create new ones?

> And may I get a permission to push to your forked repo?
Done

**Comment by nyuichi** [comment]
Some quick comments.
- I'd add "proptest" to the default features list, in order not to break existing code.
- Marking into_inner as pub means the internal structure of Serializer is exposed to everyone and we will not be able to change it in future, so I'd rather add a toplevel function like `fn serialize_in(s: impl Serialize, v: &mut Vec)` or something like that.
- To minimize the changes I'd keep the test code inside src if not necessary.

**Comment by nyuichi** [comment]
Thanks

> close this

Sure

**Pull request closed without merging**
